<?php

/**
 * ApiToken
 * 
 * @autogenerated by Phalcon Developer Tools
 * @date 2016-11-03, 14:36:00
 */
class CompanyAccess extends \Phalcon\Mvc\Model
{
    const PASSWORD = '123456';// 'cDeMity@9078CP';

    /**
     *
     * @var integer
     */
    protected $id;

    /**
     *
     * @var string
     */
    protected $registration_number;

    /**
     *
     * @var integer
     */
    protected $company_id;

    /**
     *
     * @var integer
     */
    protected $token;

    /**
     *
     * @var integer
     */
    protected $auth_username;

    /**
     *
     * @var integer
     */
    protected $allow_portal_login;

    /**
     *
     * @var integer
     */
    protected $allow_api_call;

    /**
     * Method to set the value of field id
     *
     * @param integer $id
     * @return $this
     */
    public function setId($id)
    {
        $this->id = $id;

        return $this;
    }

    /**
     * Method to set the value of field registration_number
     *
     * @param string $registration_number
     * @return $this
     */
    public function setRegistrationNumber($registration_number)
    {
        $this->registration_number = $registration_number;

        return $this;
    }

    public function setCompanyId($company_id)
    {
        $this->company_id = $company_id;
        return $this;
    }

    /**
     * Method to set the value of field token
     *
     * @param integer $token
     * @return $this
     */
    public function setToken($token)
    {
        $this->token = $token;

        return $this;
    }

    /**
     * Method to set the value of field auth_username
     *
     * @param integer $auth_username
     * @return $this
     */
    public function setAuthUsername($auth_username)
    {
        $this->auth_username = $auth_username;

        return $this;
    }

    /**
     * method for setting the field $allow_api_call
     *
     * @param $allow_api_call
     * @return $this
     */
    public function setAllowApiCall($allow_api_call)
    {
        $this->allow_api_call = $allow_api_call;
        return $this;
    }

    /**
     * method for setting the allow_portal_login field
     *
     * @param $allow_portal_login
     * @return $this
     */
    public function setAllowPortalLogin($allow_portal_login)
    {
        $this->allow_portal_login = $allow_portal_login;
        return $this;
    }

    /**
     * Returns the value of field id
     *
     * @return integer
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Returns the value of field registration_number
     *
     * @return string
     */
    public function getRegistrationNumber()
    {
        return $this->registration_number;
    }

    public function getCompanyId()
    {
        return $this->company_id;
    }

    /**
     * Returns the value of field token
     *
     * @return integer
     */
    public function getToken()
    {
        return $this->token;
    }

    /**
     * Returns the value of field auth_username
     *
     * @return integer
     */
    public function getAuthUsername()
    {
        return $this->auth_username;
    }

    /**
     * @return int
     */
    public function getAllowApiCall()
    {
        return $this->allow_api_call;
    }

    /**
     * @return int
     */
    public function getAllowPortalLogin()
    {
        return $this->allow_portal_login;
    }

    /**
     * Initialize method for model.
     */
    public function initialize()
    {
        $this->belongsTo('registration_number', 'Company', 'reg_no', array('alias' => 'Company'));
    }

    /**
     * Returns table name mapped in the model.
     *
     * @return string
     */
    public function getSource()
    {
        return 'company_access';
    }

    /**
     * Allows to query a set of records that match the specified conditions
     *
     * @param mixed $parameters
     * @return CompanyAccess[]
     */
    public static function find($parameters = null)
    {
        return parent::find($parameters);
    }

    /**
     * Allows to query the first record that match the specified conditions
     *
     * @param mixed $parameters
     * @return CompanyAccess
     */
    public static function findFirst($parameters = null)
    {
        return parent::findFirst($parameters);
    }

    /**
     * Independent Column Mapping.
     * Keys are the real names in the table and the values their names in the application
     *
     * @return array
     */
    public function columnMap()
    {
        return array(
            'id' => 'id',
            'registration_number' => 'registration_number',
            'company_id' => 'company_id',
            'token' => 'token',
            'auth_username' => 'auth_username',
            'allow_portal_login' => 'allow_portal_login',
            'allow_api_call' => 'allow_api_call'
        );
    }

    /**
     *
     * @param $registration_number
     * @param company_id
     * @param $allow_portal_login
     * @param $allow_api_call
     * @param $auth_username
     * @return CompanyAccess
     */
    public static function createOne($registration_number, $allow_portal_login, $allow_api_call, $auth_username, $company_id){
        $company_access = new CompanyAccess();
        $company_access->setToken(StringMethods::GetRandomString(24));
        $company_access->setAllowApiCall($allow_api_call);
        $company_access->setAllowPortalLogin($allow_portal_login);
        $company_access->setRegistrationNumber($registration_number);
        $company_access->setAuthUsername($auth_username);
        $company_access->setCompanyId($company_id);
        $company_access->save();
        return $company_access;
    }

}
