<?php

/**
 * CompanyParcel
 * 
 * @autogenerated by Phalcon Developer Tools
 * @date 2016-11-19, 10:00:07
 */
class CompanyParcel extends \Phalcon\Mvc\Model
{

    /**
     *
     * @var integer
     */
    protected $id;

    /**
     *
     * @var integer
     */
    protected $company_id;

    /**
     *
     * @var string
     */
    protected $waybill_number;

    /**
     *
     * @var integer
     */
    protected $company_admin_id;

    /**
     *
     * @var integer
     */
    protected $creation_source;

    /**
     * Method to set the value of field id
     *
     * @param integer $id
     * @return $this
     */
    public function setId($id)
    {
        $this->id = $id;

        return $this;
    }

    /**
     * Method to set the value of field company_id
     *
     * @param integer $company_id
     * @return $this
     */
    public function setCompanyId($company_id)
    {
        $this->company_id = $company_id;

        return $this;
    }

    /**
     * Method to set the value of field waybill_number
     *
     * @param string $waybill_number
     * @return $this
     */
    public function setWaybillNumber($waybill_number)
    {
        $this->waybill_number = $waybill_number;

        return $this;
    }

    /**
     * Method to set the value of field company_admin_id
     *
     * @param integer $company_admin_id
     * @return $this
     */
    public function setCompanyAdminId($company_admin_id)
    {
        $this->company_admin_id = $company_admin_id;

        return $this;
    }

    /**
     * Method to set the value of field creation_source
     *
     * @param integer $creation_source
     * @return $this
     */
    public function setCreationSource($creation_source)
    {
        $this->creation_source = $creation_source;

        return $this;
    }

    /**
     * Returns the value of field id
     *
     * @return integer
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Returns the value of field company_id
     *
     * @return integer
     */
    public function getCompanyId()
    {
        return $this->company_id;
    }

    /**
     * Returns the value of field waybill_number
     *
     * @return string
     */
    public function getWaybillNumber()
    {
        return $this->waybill_number;
    }

    /**
     * Returns the value of field company_admin_id
     *
     * @return integer
     */
    public function getCompanyAdminId()
    {
        return $this->company_admin_id;
    }

    /**
     * Returns the value of field creation_source
     *
     * @return integer
     */
    public function getCreationSource()
    {
        return $this->creation_source;
    }

    /**
     * Initialize method for model.
     */
    public function initialize()
    {
        $this->belongsTo('company_id', 'Company', 'id', array('alias' => 'Company'));
        $this->belongsTo('company_admin_id', 'CompanyUser', 'id', array('alias' => 'CompanyUser'));
        $this->belongsTo('waybill_number', 'Parcel', 'waybill_number', array('alias' => 'Parcel'));
    }

    /**
     * Returns table name mapped in the model.
     *
     * @return string
     */
    public function getSource()
    {
        return 'company_parcel';
    }

    /**
     * Allows to query a set of records that match the specified conditions
     *
     * @param mixed $parameters
     * @return CompanyParcel[]
     */
    public static function find($parameters = null)
    {
        return parent::find($parameters);
    }

    /**
     * Allows to query the first record that match the specified conditions
     *
     * @param mixed $parameters
     * @return CompanyParcel
     */
    public static function findFirst($parameters = null)
    {
        return parent::findFirst($parameters);
    }

    /**
     * Independent Column Mapping.
     * Keys are the real names in the table and the values their names in the application
     *
     * @return array
     */
    public function columnMap()
    {
        return array(
            'id' => 'id',
            'company_id' => 'company_id',
            'waybill_number' => 'waybill_number',
            'company_admin_id' => 'company_admin_id',
            'creation_source' => 'creation_source'
        );
    }

}
