<?php

/**
 * Distance
 * 
 * @autogenerated by Phalcon Developer Tools
 * @date 2017-01-03, 02:39:19
 */
class Distance extends \Phalcon\Mvc\Model
{

    /**
     *
     * @var integer
     */
    protected $id;

    /**
     *
     * @var integer
     */
    protected $from_city_id;

    /**
     *
     * @var integer
     */
    protected $to_city_id;

    /**
     *
     * @var integer
     */
    protected $lenght;

    /**
     * Method to set the value of field id
     *
     * @param integer $id
     * @return $this
     */
    public function setId($id)
    {
        $this->id = $id;

        return $this;
    }

    /**
     * Method to set the value of field from_city_id
     *
     * @param integer $from_city_id
     * @return $this
     */
    public function setFromCityId($from_city_id)
    {
        $this->from_city_id = $from_city_id;

        return $this;
    }

    /**
     * Method to set the value of field to_city_id
     *
     * @param integer $to_city_id
     * @return $this
     */
    public function setToCityId($to_city_id)
    {
        $this->to_city_id = $to_city_id;

        return $this;
    }

    /**
     * Method to set the value of field lenght
     *
     * @param integer $lenght
     * @return $this
     */
    public function setLenght($lenght)
    {
        $this->lenght = $lenght;

        return $this;
    }

    /**
     * Returns the value of field id
     *
     * @return integer
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Returns the value of field from_city_id
     *
     * @return integer
     */
    public function getFromCityId()
    {
        return $this->from_city_id;
    }

    /**
     * Returns the value of field to_city_id
     *
     * @return integer
     */
    public function getToCityId()
    {
        return $this->to_city_id;
    }

    /**
     * Returns the value of field lenght
     *
     * @return integer
     */
    public function getLenght()
    {
        return $this->lenght;
    }

    /**
     * Initialize method for model.
     */
    public function initialize()
    {
        $this->belongsTo('from_city_id', 'City', 'id', array('alias' => 'City'));
        $this->belongsTo('to_city_id', 'City', 'id', array('alias' => 'City'));
    }

    /**
     * Returns table name mapped in the model.
     *
     * @return string
     */
    public function getSource()
    {
        return 'distance';
    }

    /**
     * Allows to query a set of records that match the specified conditions
     *
     * @param mixed $parameters
     * @return Distance[]
     */
    public static function find($parameters = null)
    {
        return parent::find($parameters);
    }

    /**
     * Allows to query the first record that match the specified conditions
     *
     * @param mixed $parameters
     * @return Distance
     */
    public static function findFirst($parameters = null)
    {
        return parent::findFirst($parameters);
    }

    /**
     * Independent Column Mapping.
     * Keys are the real names in the table and the values their names in the application
     *
     * @return array
     */
    public function columnMap()
    {
        return array(
            'id' => 'id',
            'from_city_id' => 'from_city_id',
            'to_city_id' => 'to_city_id',
            'lenght' => 'lenght'
        );
    }

}
