<?php

/**
 * ExportedParcel
 * 
 * @autogenerated by Phalcon Developer Tools
 * @date 2017-01-13, 16:48:38
 */
class ExportedParcel extends \Phalcon\Mvc\Model
{

    /**
     *
     * @var integer
     */
    protected $id;

    /**
     *
     * @var string
     */
    protected $parcel_id;

    /**
     *
     * @var integer
     */
    protected $export_agent_id;

    /**
     *
     * @var string
     */
    protected $agent_tracking_number;

    /**
     * Method to set the value of field id
     *
     * @param integer $id
     * @return $this
     */
    public function setId($id)
    {
        $this->id = $id;

        return $this;
    }

    /**
     * Method to set the value of field parcel_id
     *
     * @param string $parcel_id
     * @return $this
     */
    public function setParcelId($parcel_id)
    {
        $this->parcel_id = $parcel_id;

        return $this;
    }

    /**
     * Method to set the value of field export_agent_id
     *
     * @param integer $export_agent_id
     * @return $this
     */
    public function setExportAgentId($export_agent_id)
    {
        $this->export_agent_id = $export_agent_id;

        return $this;
    }

    /**
     * Method to set the value of field agent_tracking_number
     *
     * @param string $agent_tracking_number
     * @return $this
     */
    public function setAgentTrackingNumber($agent_tracking_number)
    {
        $this->agent_tracking_number = $agent_tracking_number;

        return $this;
    }

    /**
     * Returns the value of field id
     *
     * @return integer
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Returns the value of field parcel_id
     *
     * @return string
     */
    public function getParcelId()
    {
        return $this->parcel_id;
    }

    /**
     * Returns the value of field export_agent_id
     *
     * @return integer
     */
    public function getExportAgentId()
    {
        return $this->export_agent_id;
    }

    /**
     * Returns the value of field agent_tracking_number
     *
     * @return string
     */
    public function getAgentTrackingNumber()
    {
        return $this->agent_tracking_number;
    }

    /**
     * Initialize method for model.
     */
    public function initialize()
    {
        $this->belongsTo('export_agent_id', 'ExportAgent', 'id', array('alias' => 'ExportAgent'));
        $this->belongsTo('parcel_id', 'Parcel', 'id', array('alias' => 'Parcel'));
    }

    /**
     * Returns table name mapped in the model.
     *
     * @return string
     */
    public function getSource()
    {
        return 'exported_parcel';
    }

    /**
     * Allows to query a set of records that match the specified conditions
     *
     * @param mixed $parameters
     * @return ExportedParcel[]
     */
    public static function find($parameters = null)
    {
        return parent::find($parameters);
    }

    /**
     * Allows to query the first record that match the specified conditions
     *
     * @param mixed $parameters
     * @return ExportedParcel
     */
    public static function findFirst($parameters = null)
    {
        return parent::findFirst($parameters);
    }

    /**
     * Independent Column Mapping.
     * Keys are the real names in the table and the values their names in the application
     *
     * @return array
     */
    public function columnMap()
    {
        return array(
            'id' => 'id',
            'parcel_id' => 'parcel_id',
            'export_agent_id' => 'export_agent_id',
            'agent_tracking_number' => 'agent_tracking_number'
        );
    }

    /**
     * @param $offset
     * @param $count
     * @param $filter_by
     * @param $fetch_with
     * @param bool|false $paginate bhh
     * @return array
     */
    /**
     * @param $offset
     * @param $count
     * @param $filter_by
     * @param $fetch_with
     * @param bool|false $paginate bhh
     * @return array
     */
    public static function fetchAll($offset, $count, $filter_by, $fetch_with, $paginate = false){
        $builder = new \Phalcon\Mvc\Model\Query\Builder();
        $builder->addFrom('ExportedParcel');
        $columns = ['ExportedParcel.*'];
        $bind = [];
        if ($paginate) {
            $builder = $builder->limit($count, $offset);
        }

        $builder->columns($columns);


        if(isset($filter_by['export_agent_id'])){
            $builder->where("ExportParcel.export_agent_id = :export_agent_id:");
            $bind['export_agent_id'] = $filter_by['export_agent_id'];
        }

        if(isset($filter_by['waybill_number'])){
            $builder->where("Parcel.waybill_number = :waybill_number:");
            $bind['waybill_number'] = $filter_by['waybill_number'];
        }


        if(isset($fetch_with['with_parcel'])){
            $builder->innerJoin('Parcel', 'ExportedParcel.parcel_id = Parcel.id', 'Parcel');
            $builder->innerJoin('Address', 'Address.id = Parcel.receiver_address_id', 'Address');
            $builder->innerJoin('Country', 'Country.id = Address.country_id', 'Country');
            //$builder->where("Country.id = :country_id:");
            //$bind['country_id'] = $filter_by['country_id'];
        }


//        if(isset($fetch_with['with_staff'])){
//            $builder->innerJoin('Admin', 'Admin.staff_id = BmCentre.staff_id', 'Admin');
//        }

        $data = $builder->getQuery()->execute($bind);


        $zones = [];
        foreach ($data as $item) {
            $zones[] = $item->toArray();
        }
        return $zones;
    }

}
