<?php

/**
 * LttlBilling
 * 
 * @autogenerated by Phalcon Developer Tools
 * @date 2017-01-17, 12:37:46
 */
class LttlBilling extends \Phalcon\Mvc\Model
{

    /**
     *
     * @var integer
     */
    protected $id;

    /**
     *
     * @var integer
     */
    protected $zone_id;

    /**
     *
     * @var integer
     */
    protected $min_charge;

    /**
     *
     * @var integer
     */
    protected $charge_per_kg;

    /**
     *
     * @var integer
     */
    protected $onforwarding_charge;

    /**
     * Method to set the value of field id
     *
     * @param integer $id
     * @return $this
     */
    public function setId($id)
    {
        $this->id = $id;

        return $this;
    }

    /**
     * Method to set the value of field zone_id
     *
     * @param integer $zone_id
     * @return $this
     */
    public function setZoneId($zone_id)
    {
        $this->zone_id = $zone_id;

        return $this;
    }

    /**
     * Method to set the value of field min_charge
     *
     * @param integer $min_charge
     * @return $this
     */
    public function setMinCharge($min_charge)
    {
        $this->min_charge = $min_charge;

        return $this;
    }

    /**
     * Method to set the value of field charge_per_kg
     *
     * @param integer $charge_per_kg
     * @return $this
     */
    public function setChargePerKg($charge_per_kg)
    {
        $this->charge_per_kg = $charge_per_kg;

        return $this;
    }

    /**
     * Method to set the value of field onforwarding_charge
     *
     * @param integer $onforwarding_charge
     * @return $this
     */
    public function setOnforwardingCharge($onforwarding_charge)
    {
        $this->onforwarding_charge = $onforwarding_charge;

        return $this;
    }

    /**
     * Returns the value of field id
     *
     * @return integer
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Returns the value of field zone_id
     *
     * @return integer
     */
    public function getZoneId()
    {
        return $this->zone_id;
    }

    /**
     * Returns the value of field min_charge
     *
     * @return integer
     */
    public function getMinCharge()
    {
        return $this->min_charge;
    }

    /**
     * Returns the value of field charge_per_kg
     *
     * @return integer
     */
    public function getChargePerKg()
    {
        return $this->charge_per_kg;
    }

    /**
     * Returns the value of field onforwarding_charge
     *
     * @return integer
     */
    public function getOnforwardingCharge()
    {
        return $this->onforwarding_charge;
    }

    /**
     * Initialize method for model.
     */
    public function initialize()
    {
        $this->belongsTo('zone_id', 'Zone', 'id', array('alias' => 'Zone'));
    }

    /**
     * Returns table name mapped in the model.
     *
     * @return string
     */
    public function getSource()
    {
        return 'lttl_billing';
    }

    /**
     * Allows to query a set of records that match the specified conditions
     *
     * @param mixed $parameters
     * @return LttlBilling[]
     */
    public static function find($parameters = null)
    {
        return parent::find($parameters);
    }

    /**
     * Allows to query the first record that match the specified conditions
     *
     * @param mixed $parameters
     * @return LttlBilling
     */
    public static function findFirst($parameters = null)
    {
        return parent::findFirst($parameters);
    }

    /**
     * Independent Column Mapping.
     * Keys are the real names in the table and the values their names in the application
     *
     * @return array
     */
    public function columnMap()
    {
        return array(
            'id' => 'id',
            'zone_id' => 'zone_id',
            'min_charge' => 'min_charge',
            'charge_per_kg' => 'charge_per_kg',
            'onforwarding_charge' => 'onforwarding_charge'
        );
    }

}
