<?php

/**
 * OldRemittance
 * 
 * @autogenerated by Phalcon Developer Tools
 * @date 2017-01-31, 14:11:28
 */
class OldRemittance extends \Phalcon\Mvc\Model
{

    /**
     *
     * @var integer
     */
    protected $Id;

    /**
     *
     * @var string
     */
    protected $ClientName;

    /**
     *
     * @var string
     */
    protected $DeliveryLocation;

    /**
     *
     * @var string
     */
    protected $StatusUpdate;

    /**
     *
     * @var string
     */
    protected $hawbstandard;

    /**
     *
     * @var string
     */
    protected $hawb;

    /**
     *
     * @var string
     */
    protected $RefNo;

    /**
     *
     * @var string
     */
    protected $pickup_date;

    /**
     *
     * @var string
     */
    protected $Location;

    /**
     *
     * @var string
     */
    protected $customer_reference;

    /**
     *
     * @var string
     */
    protected $customer;

    /**
     *
     * @var string
     */
    protected $Column1;

    /**
     *
     * @var string
     */
    protected $agent;

    /**
     *
     * @var string
     */
    protected $value;

    /**
     *
     * @var string
     */
    protected $conee_name;

    /**
     *
     * @var string
     */
    protected $ssr_log_code;

    /**
     *
     * @var string
     */
    protected $ssr_logs_event_date;

    /**
     *
     * @var string
     */
    protected $sts;

    /**
     *
     * @var string
     */
    protected $AmountDue;

    /**
     *
     * @var string
     */
    protected $RemittanceDate;

    /**
     *
     * @var string
     */
    protected $DaysinOps;

    /**
     *
     * @var string
     */
    protected $Remittance;

    /**
     *
     * @var string
     */
    protected $Amount;

    /**
     *
     * @var string
     */
    protected $PaymentCode;

    /**
     *
     * @var string
     */
    protected $CCash;

    /**
     *
     * @var string
     */
    protected $PPOS;

    /**
     *
     * @var string
     */
    protected $KKongaDL;

    /**
     *
     * @var string
     */
    protected $RReturned;

    /**
     *
     * @var string
     */
    protected $EffDate;

    /**
     *
     * @var string
     */
    protected $narration;

    /**
     * Method to set the value of field Id
     *
     * @param integer $Id
     * @return $this
     */
    public function setId($Id)
    {
        $this->Id = $Id;

        return $this;
    }

    /**
     * Method to set the value of field ClientName
     *
     * @param string $ClientName
     * @return $this
     */
    public function setClientName($ClientName)
    {
        $this->ClientName = $ClientName;

        return $this;
    }

    /**
     * Method to set the value of field DeliveryLocation
     *
     * @param string $DeliveryLocation
     * @return $this
     */
    public function setDeliveryLocation($DeliveryLocation)
    {
        $this->DeliveryLocation = $DeliveryLocation;

        return $this;
    }

    /**
     * Method to set the value of field StatusUpdate
     *
     * @param string $StatusUpdate
     * @return $this
     */
    public function setStatusUpdate($StatusUpdate)
    {
        $this->StatusUpdate = $StatusUpdate;

        return $this;
    }

    /**
     * Method to set the value of field hawbstandard
     *
     * @param string $hawbstandard
     * @return $this
     */
    public function setHawbstandard($hawbstandard)
    {
        $this->hawbstandard = $hawbstandard;

        return $this;
    }

    /**
     * Method to set the value of field hawb
     *
     * @param string $hawb
     * @return $this
     */
    public function setHawb($hawb)
    {
        $this->hawb = $hawb;

        return $this;
    }

    /**
     * Method to set the value of field RefNo
     *
     * @param string $RefNo
     * @return $this
     */
    public function setRefNo($RefNo)
    {
        $this->RefNo = $RefNo;

        return $this;
    }

    /**
     * Method to set the value of field pickup_date
     *
     * @param string $pickup_date
     * @return $this
     */
    public function setPickupDate($pickup_date)
    {
        $this->pickup_date = $pickup_date;

        return $this;
    }

    /**
     * Method to set the value of field Location
     *
     * @param string $Location
     * @return $this
     */
    public function setLocation($Location)
    {
        $this->Location = $Location;

        return $this;
    }

    /**
     * Method to set the value of field customer_reference
     *
     * @param string $customer_reference
     * @return $this
     */
    public function setCustomerReference($customer_reference)
    {
        $this->customer_reference = $customer_reference;

        return $this;
    }

    /**
     * Method to set the value of field customer
     *
     * @param string $customer
     * @return $this
     */
    public function setCustomer($customer)
    {
        $this->customer = $customer;

        return $this;
    }

    /**
     * Method to set the value of field Column1
     *
     * @param string $Column1
     * @return $this
     */
    public function setColumn1($Column1)
    {
        $this->Column1 = $Column1;

        return $this;
    }

    /**
     * Method to set the value of field agent
     *
     * @param string $agent
     * @return $this
     */
    public function setAgent($agent)
    {
        $this->agent = $agent;

        return $this;
    }

    /**
     * Method to set the value of field value
     *
     * @param string $value
     * @return $this
     */
    public function setValue($value)
    {
        $this->value = $value;

        return $this;
    }

    /**
     * Method to set the value of field conee_name
     *
     * @param string $conee_name
     * @return $this
     */
    public function setConeeName($conee_name)
    {
        $this->conee_name = $conee_name;

        return $this;
    }

    /**
     * Method to set the value of field ssr_log_code
     *
     * @param string $ssr_log_code
     * @return $this
     */
    public function setSsrLogCode($ssr_log_code)
    {
        $this->ssr_log_code = $ssr_log_code;

        return $this;
    }

    /**
     * Method to set the value of field ssr_logs_event_date
     *
     * @param string $ssr_logs_event_date
     * @return $this
     */
    public function setSsrLogsEventDate($ssr_logs_event_date)
    {
        $this->ssr_logs_event_date = $ssr_logs_event_date;

        return $this;
    }

    /**
     * Method to set the value of field sts
     *
     * @param string $sts
     * @return $this
     */
    public function setSts($sts)
    {
        $this->sts = $sts;

        return $this;
    }

    /**
     * Method to set the value of field AmountDue
     *
     * @param string $AmountDue
     * @return $this
     */
    public function setAmountDue($AmountDue)
    {
        $this->AmountDue = $AmountDue;

        return $this;
    }

    /**
     * Method to set the value of field RemittanceDate
     *
     * @param string $RemittanceDate
     * @return $this
     */
    public function setRemittanceDate($RemittanceDate)
    {
        $this->RemittanceDate = $RemittanceDate;

        return $this;
    }

    /**
     * Method to set the value of field DaysinOps
     *
     * @param string $DaysinOps
     * @return $this
     */
    public function setDaysinOps($DaysinOps)
    {
        $this->DaysinOps = $DaysinOps;

        return $this;
    }

    /**
     * Method to set the value of field Remittance
     *
     * @param string $Remittance
     * @return $this
     */
    public function setRemittance($Remittance)
    {
        $this->Remittance = $Remittance;

        return $this;
    }

    /**
     * Method to set the value of field Amount
     *
     * @param string $Amount
     * @return $this
     */
    public function setAmount($Amount)
    {
        $this->Amount = $Amount;

        return $this;
    }

    /**
     * Method to set the value of field PaymentCode
     *
     * @param string $PaymentCode
     * @return $this
     */
    public function setPaymentCode($PaymentCode)
    {
        $this->PaymentCode = $PaymentCode;

        return $this;
    }

    /**
     * Method to set the value of field CCash
     *
     * @param string $CCash
     * @return $this
     */
    public function setCCash($CCash)
    {
        $this->CCash = $CCash;

        return $this;
    }

    /**
     * Method to set the value of field PPOS
     *
     * @param string $PPOS
     * @return $this
     */
    public function setPPOS($PPOS)
    {
        $this->PPOS = $PPOS;

        return $this;
    }

    /**
     * Method to set the value of field KKongaDL
     *
     * @param string $KKongaDL
     * @return $this
     */
    public function setKKongaDL($KKongaDL)
    {
        $this->KKongaDL = $KKongaDL;

        return $this;
    }

    /**
     * Method to set the value of field RReturned
     *
     * @param string $RReturned
     * @return $this
     */
    public function setRReturned($RReturned)
    {
        $this->RReturned = $RReturned;

        return $this;
    }

    /**
     * Method to set the value of field EffDate
     *
     * @param string $EffDate
     * @return $this
     */
    public function setEffDate($EffDate)
    {
        $this->EffDate = $EffDate;

        return $this;
    }

    /**
     * Method to set the value of field narration
     *
     * @param string $narration
     * @return $this
     */
    public function setNarration($narration)
    {
        $this->narration = $narration;

        return $this;
    }

    /**
     * Returns the value of field Id
     *
     * @return integer
     */
    public function getId()
    {
        return $this->Id;
    }

    /**
     * Returns the value of field ClientName
     *
     * @return string
     */
    public function getClientName()
    {
        return $this->ClientName;
    }

    /**
     * Returns the value of field DeliveryLocation
     *
     * @return string
     */
    public function getDeliveryLocation()
    {
        return $this->DeliveryLocation;
    }

    /**
     * Returns the value of field StatusUpdate
     *
     * @return string
     */
    public function getStatusUpdate()
    {
        return $this->StatusUpdate;
    }

    /**
     * Returns the value of field hawbstandard
     *
     * @return string
     */
    public function getHawbstandard()
    {
        return $this->hawbstandard;
    }

    /**
     * Returns the value of field hawb
     *
     * @return string
     */
    public function getHawb()
    {
        return $this->hawb;
    }

    /**
     * Returns the value of field RefNo
     *
     * @return string
     */
    public function getRefNo()
    {
        return $this->RefNo;
    }

    /**
     * Returns the value of field pickup_date
     *
     * @return string
     */
    public function getPickupDate()
    {
        return $this->pickup_date;
    }

    /**
     * Returns the value of field Location
     *
     * @return string
     */
    public function getLocation()
    {
        return $this->Location;
    }

    /**
     * Returns the value of field customer_reference
     *
     * @return string
     */
    public function getCustomerReference()
    {
        return $this->customer_reference;
    }

    /**
     * Returns the value of field customer
     *
     * @return string
     */
    public function getCustomer()
    {
        return $this->customer;
    }

    /**
     * Returns the value of field Column1
     *
     * @return string
     */
    public function getColumn1()
    {
        return $this->Column1;
    }

    /**
     * Returns the value of field agent
     *
     * @return string
     */
    public function getAgent()
    {
        return $this->agent;
    }

    /**
     * Returns the value of field value
     *
     * @return string
     */
    public function getValue()
    {
        return $this->value;
    }

    /**
     * Returns the value of field conee_name
     *
     * @return string
     */
    public function getConeeName()
    {
        return $this->conee_name;
    }

    /**
     * Returns the value of field ssr_log_code
     *
     * @return string
     */
    public function getSsrLogCode()
    {
        return $this->ssr_log_code;
    }

    /**
     * Returns the value of field ssr_logs_event_date
     *
     * @return string
     */
    public function getSsrLogsEventDate()
    {
        return $this->ssr_logs_event_date;
    }

    /**
     * Returns the value of field sts
     *
     * @return string
     */
    public function getSts()
    {
        return $this->sts;
    }

    /**
     * Returns the value of field AmountDue
     *
     * @return string
     */
    public function getAmountDue()
    {
        return $this->AmountDue;
    }

    /**
     * Returns the value of field RemittanceDate
     *
     * @return string
     */
    public function getRemittanceDate()
    {
        return $this->RemittanceDate;
    }

    /**
     * Returns the value of field DaysinOps
     *
     * @return string
     */
    public function getDaysinOps()
    {
        return $this->DaysinOps;
    }

    /**
     * Returns the value of field Remittance
     *
     * @return string
     */
    public function getRemittance()
    {
        return $this->Remittance;
    }

    /**
     * Returns the value of field Amount
     *
     * @return string
     */
    public function getAmount()
    {
        return $this->Amount;
    }

    /**
     * Returns the value of field PaymentCode
     *
     * @return string
     */
    public function getPaymentCode()
    {
        return $this->PaymentCode;
    }

    /**
     * Returns the value of field CCash
     *
     * @return string
     */
    public function getCCash()
    {
        return $this->CCash;
    }

    /**
     * Returns the value of field PPOS
     *
     * @return string
     */
    public function getPPOS()
    {
        return $this->PPOS;
    }

    /**
     * Returns the value of field KKongaDL
     *
     * @return string
     */
    public function getKKongaDL()
    {
        return $this->KKongaDL;
    }

    /**
     * Returns the value of field RReturned
     *
     * @return string
     */
    public function getRReturned()
    {
        return $this->RReturned;
    }

    /**
     * Returns the value of field EffDate
     *
     * @return string
     */
    public function getEffDate()
    {
        return $this->EffDate;
    }

    /**
     * Returns the value of field narration
     *
     * @return string
     */
    public function getNarration()
    {
        return $this->narration;
    }

    /**
     * Returns table name mapped in the model.
     *
     * @return string
     */
    public function getSource()
    {
        return 'old_remittance';
    }

    /**
     * Allows to query a set of records that match the specified conditions
     *
     * @param mixed $parameters
     * @return OldRemittance[]
     */
    public static function find($parameters = null)
    {
        return parent::find($parameters);
    }

    /**
     * Allows to query the first record that match the specified conditions
     *
     * @param mixed $parameters
     * @return OldRemittance
     */
    public static function findFirst($parameters = null)
    {
        return parent::findFirst($parameters);
    }

    /**
     * Independent Column Mapping.
     * Keys are the real names in the table and the values their names in the application
     *
     * @return array
     */
    public function columnMap()
    {
        return array(
            'Id' => 'Id',
            'ClientName' => 'ClientName',
            'DeliveryLocation' => 'DeliveryLocation',
            'StatusUpdate' => 'StatusUpdate',
            'hawbstandard' => 'hawbstandard',
            'hawb' => 'hawb',
            'RefNo' => 'RefNo',
            'pickup_date' => 'pickup_date',
            'Location' => 'Location',
            'customer_reference' => 'customer_reference',
            'customer' => 'customer',
            'Column1' => 'Column1',
            'agent' => 'agent',
            'value' => 'value',
            'conee_name' => 'conee_name',
            'ssr_log_code' => 'ssr_log_code',
            'ssr_logs_event_date' => 'ssr_logs_event_date',
            'sts' => 'sts',
            'AmountDue' => 'AmountDue',
            'RemittanceDate' => 'RemittanceDate',
            'DaysinOps' => 'DaysinOps',
            'Remittance' => 'Remittance',
            'Amount' => 'Amount',
            'PaymentCode' => 'PaymentCode',
            'CCash' => 'CCash',
            'PPOS' => 'PPOS',
            'KKongaDL' => 'KKongaDL',
            'RReturned' => 'RReturned',
            'EffDate' => 'EffDate',
            'narration' => 'narration'
        );
    }

}
