<?php

/**
 * TransitTime
 * 
 * @autogenerated by Phalcon Developer Tools
 * @date 2016-07-14, 15:29:46
 */
class TransitTime extends \Phalcon\Mvc\Model
{

    /**
     *
     * @var integer
     */
    protected $id;

    /**
     *
     * @var integer
     */
    protected $from_branch_id;

    /**
     *
     * @var integer
     */
    protected $to_branch_id;

    /**
     *
     * @var integer
     */
    protected $hours;

    /**
     * Method to set the value of field id
     *
     * @param integer $id
     * @return $this
     */
    public function setId($id)
    {
        $this->id = $id;

        return $this;
    }

    /**
     * Method to set the value of field from_branch_id
     *
     * @param integer $from_branch_id
     * @return $this
     */
    public function setFromBranchId($from_branch_id)
    {
        $this->from_branch_id = $from_branch_id;

        return $this;
    }

    /**
     * Method to set the value of field to_branch_id
     *
     * @param integer $to_branch_id
     * @return $this
     */
    public function setToBranchId($to_branch_id)
    {
        $this->to_branch_id = $to_branch_id;

        return $this;
    }

    /**
     * Method to set the value of field hours
     *
     * @param integer $hours
     * @return $this
     */
    public function setHours($hours)
    {
        $this->hours = $hours;

        return $this;
    }

    /**
     * Returns the value of field id
     *
     * @return integer
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Returns the value of field from_branch_id
     *
     * @return integer
     */
    public function getFromBranchId()
    {
        return $this->from_branch_id;
    }

    /**
     * Returns the value of field to_branch_id
     *
     * @return integer
     */
    public function getToBranchId()
    {
        return $this->to_branch_id;
    }

    /**
     * Returns the value of field hours
     *
     * @return integer
     */
    public function getHours()
    {
        return $this->hours;
    }

    /**
     * Initialize method for model.
     */
    public function initialize()
    {
        $this->belongsTo('from_branch_id', 'Branch', 'id', array('alias' => 'Branch'));
        $this->belongsTo('to_branch_id', 'Branch', 'id', array('alias' => 'Branch'));
    }

    /**
     * Returns table name mapped in the model.
     *
     * @return string
     */
    public function getSource()
    {
        return 'transit_time';
    }

    /**
     * Allows to query a set of records that match the specified conditions
     *
     * @param mixed $parameters
     * @return TransitTime[]
     */
    public static function find($parameters = null)
    {
        return parent::find($parameters);
    }

    /**
     * Allows to query the first record that match the specified conditions
     *
     * @param mixed $parameters
     * @return TransitTime
     */
    public static function findFirst($parameters = null)
    {
        return parent::findFirst($parameters);
    }

    /**
     * Independent Column Mapping.
     * Keys are the real names in the table and the values their names in the application
     *
     * @return array
     */
    public function columnMap()
    {
        return array(
            'id' => 'id',
            'from_branch_id' => 'from_branch_id',
            'to_branch_id' => 'to_branch_id',
            'hours' => 'hours'
        );
    }

    public function initData($from_branch_id, $to_branch_id, $hours){
        $this->setFromBranchId($from_branch_id)
            ->setToBranchId($to_branch_id)
            ->setHours($hours);
    }

    public function getData(){
        return [
            'id' => $this->getId(),
            'to_branch_id' => $this->getToBranchId(),
            'from_branch_id' => $this->getFromBranchId(),
            'hours' => $this->getHours()
        ];
    }


    public static function fetchById($id){
        return TransitTime::findFirst([
            'id = :id:',
            'bind' => ['id' => $id]
        ]);
    }

    public static function fetchByLink($to_branch_id, $from_branch_id){
        return TransitTime::findFirst([
            '(
            (TransitTime.to_branch_id = :branch_id: AND TransitTime.from_branch_id = :other_branch_id:)
            OR (TransitTime.to_branch_id = :other_branch_id: AND TransitTime.from_branch_id = :branch_id:)
            )',
            'bind' => ['branch_id' => $to_branch_id, 'other_branch_id' => $from_branch_id]
        ]);
    }

    /**
     * @param $transit_time_info - [to_branch_id, from_branch_id, zone_id]
     * @return array
     */
    public static function saveTransitTime($transit_time_info){
        $bad_transit_time_info = [];

        foreach ($transit_time_info as $item) {
            try {
                $cell = TransitTime::fetchByLink($item['to_branch_id'], $item['from_branch_id']);
                if ($cell == false) {
                    $cell = new TransitTime();
                    $cell->initData($item['to_branch_id'], $item['from_branch_id'], $item['hours']);
                } else {
                    $cell->setHours($item['hours']);
                }
                $cell->save();
            } catch (Exception $e) {
                $bad_transit_time_info[] = $item;
            }
        }
        return $bad_transit_time_info;
    }

    public static function fetchAll($filter_by){
        $obj = new TransitTime();
        $builder = $obj->getModelsManager()->createBuilder()
            ->columns(['TransitTime.*', 'ToBranch.*', 'ToBranchState.*', 'FromBranch.*', 'FromBranchState.*'])
            ->from('TransitTime')
            ->innerJoin('FromBranch', 'FromBranch.id = TransitTime.from_branch_id', 'FromBranch')
            ->innerJoin('FromBranchState', 'FromBranchState.id = FromBranch.state_id', 'FromBranchState')
            ->innerJoin('ToBranch', 'ToBranch.id = TransitTime.to_branch_id', 'ToBranch')
            ->innerJoin('ToBranchState', 'ToBranchState.id = ToBranch.state_id', 'ToBranchState');

        $where = [];
        $bind = [];

        if (isset($filter_by['branch_id']) and isset($filter_by['other_branch_id'])){
            $where[] = '(
            (TransitTime.to_branch_id = :branch_id: AND TransitTime.from_branch_id = :other_branch_id:)
            OR (TransitTime.to_branch_id = :other_branch_id: AND TransitTime.from_branch_id = :branch_id:)
            )';
            $bind['branch_id'] = $filter_by['branch_id'];
            $bind['other_branch_id'] = $filter_by['other_branch_id'];
        } else if (isset($filter_by['branch_id'])){
            $where[] = '(TransitTime.to_branch_id = :branch_id: OR TransitTime.from_branch_id = :branch_id:)';
            $bind['branch_id'] = $filter_by['branch_id'];
        }

        $builder->where(join(' AND ', $where));
        $data = $builder->getQuery()->execute($bind);

        $result = [];
        foreach ($data as $item){
            $transit_time_itme  = $item->transitTime->getData();
            $transit_time_itme['to_branch'] = $item->toBranch->getData();
            $transit_time_itme['to_branch']['state'] = $item->toBranchState->getData();
            $transit_time_itme['from_branch'] = $item->fromBranch->getData();
            $transit_time_itme['from_branch']['state'] = $item->fromBranchState->getData();

            $result[] = $transit_time_itme;
        }
        return $result;
    }
}
